### ISSUE TITLE
listings location information

### ISSUE THREAD

**Issue by boxysean** [idamantium/Osclass#25]
site: http://idamantium.webfactional.com/SuperNet/index.php?page=search&sCategory=31
- There is no "primary" neighborhood information.

**Comment by idamantium** [comment]
where would primary neighborhood information go? Is this for the search or for the listings? or something else?

**Comment by boxysean** [comment]
e.g., what exists now:

My Computer
(Hanna Mart) - April 17, 2013
I'm quitting code.

Should become:

My Computer
Bushwick - near Hanna Mart - April 17, 2013
I'm quitting code.
