### ISSUE TITLE
Front page location sidebar

### ISSUE THREAD

**Issue by boxysean** [idamantium/Osclass#27]
site: http://idamantium.webfactional.com/SuperNet/

== Instead of this:

Location

Cain's Tavern (1)
Grumpy's (2)
Hanna Mart (2)

== Have this:

Location

Bushwick <link to all of bushwick items>
- Cain's Tavern (1)
- Hanna Mart (2)

Greenpoint
- Grumpy's (2)

**Comment by idamantium** [comment]
changes it to show neighborhoods. how did you get the drop downs on the listings to show the right subset of neighborhood locations? this probably needs a similar solution.

**Comment by boxysean** [comment]
I think the change you made is good... going to leave it that for now.

Not looking for a dropdown, but a breakdown of locations.

Removing from MVP milestone.
