### ISSUE TITLE
search items by neighborhood

### ISSUE THREAD

**Issue by boxysean** [idamantium/Osclass#34]
site: http://idamantium.webfactional.com/SuperNet/index.php?page=search&sCategory=31
- Cannot search / filter / sort by neighborhood.

**Comment by idamantium** [comment]
Hm... Neighborhood is mapped to City in osclass, but there doesn't seem to be a search function written for city, unless I overlooked it. Made a note in the code where it needs to be changed as well and commended out the existing location option.
